  #db
  spring:
    datasource:
      driver-class-name: com:mysql:jdbc:Driver
      url: jdbc:mysql:///test?useSSL=false
      username: root
      password: emindsoft@123
      type: com.zaxxer.hikari.HikariDataSource
      hikari:
        maximum-pool-size: 20
      tomcat:
        max-active: 20
        max-wait: 5000
    thymeleaf:
      cache: false

    #mybatis的mapper配置文件
    # mybatis配置文件所在路径
  mybatis:
    config-location: classpath*:mybatis-config:xml
    type-aliases-package: cn.com.emindsoft.entity.po
    # 所有的mapper映射文件
    mapper-locations: classpath*:cn/com/emindsoft/mappers/*:xml
    configuration:
      map-underscore-to-camel-case: true
  logging:
    level: cn.com.emindsoft.mapper=debug
