#db
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.35:3306/base_framework?useSSL=false
    username: root
    password: EmindSoft@123
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 20
    tomcat:
      max-active: 20
      max-wait: 5000
  thymeleaf:
    cache: false
  redis:
    host: 192.168.0.35
    port: 6379
    database: 0
  resources:
      static-locations: classpath:/statics/,classpath:/views/
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  jmx:
    enabled: false


#mybatis的mapper配置文件
# mybatis配置文件所在路径
mybatis:
  config-location: classpath*:mybatis-config.xml
  type-aliases-package: cn.com.emindsoft.entity.po
  # 所有的mapper映射文件
  mapper-locations: classpath*:cn.com.emindsoft.mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

swagger:
  enable: true

