  #db
  spring:
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.0.35:3306/base_framework?useSSL=false
      username: root
      password: EmindSoft@123
      type: com.zaxxer.hikari.HikariDataSource
      hikari:
        maximum-pool-size: 20
      tomcat:
        max-active: 20
        max-wait: 5000
    thymeleaf:
      cache: false
    redis:
      host: 192.168.0.35
      port: 6379
      database: 0


